name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Master
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup Java
        uses: actions/setup-java@v1.0.0
        with:
          version: 11.x
      - name: Build
        run: |
          ./gradlew verifyPlugin
      - name: Publish Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: IntelliJ Move Tab
          path: build/libs/
