name: Publish Plugin

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+-?*'
      
jobs:
  build:
    name: Build, Verify, and Publish Plugin
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup Java
        uses: actions/setup-java@v1.0.0
        with:
          version: 11.x
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        env:
          CI: true
        run: |
          ./gradlew --no-daemon verifyPlugin
      - name: Publish Artifact
        uses: actions/upload-artifact@v1
        with:
          name: intellij-move-tab
          path: build/libs
      - name: Publish Plugin
        env:
          publishToken: ${{ secrets.JETBRAINS_HUB_TOKEN }}
        run: |
          ./gradlew --no-daemon publishPlugin
