name: Publish Plugin

on:
    push:
        tags: 'v[0-9]+.[0-9]+.[0-9]+-?*'

jobs:
    build:
        name: Build, Verify, and Publish Plugin
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout
                uses: actions/checkout@v3.1.0
            -   name: Setup Java
                uses: actions/setup-java@v3.5.1
                with:
                    java-version: 17.x
                    distribution: temurin
            -   name: Gradle Cache
                uses: actions/cache@v3.0.10
                with:
                    path: ~/.gradle/caches
                    key: ${{ runner.os }}-gradle
            -   name: Build
                env:
                    CI: true
                run: |
                    ./gradlew --no-daemon verifyPlugin
            -   name: Publish Artifact
                uses: actions/upload-artifact@v3.1.0
                with:
                    name: intellij-move-tab
                    path: build/libs
            -   name: Publish Plugin
                env:
                    publishToken: ${{ secrets.JETBRAINS_HUB_TOKEN }}
                run: |
                    ./gradlew --no-daemon publishPlugin
