name: Build and Verify Plugin

on:
    push:
        branches: '*'
        tags-ignore: '*'
    pull_request:
        branches: '*'

jobs:
    build:
        name: Build and Verify Plugin
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout
                uses: actions/checkout@v3.1.0
            -   name: Setup Java
                uses: actions/setup-java@v4.7.1
                with:
                    java-version: 17.x
                    distribution: temurin
            -   name: Use Gradle Cache
                uses: actions/cache@v4
                with:
                    path: ~/.gradle/caches
                    key: ${{ runner.os }}-gradle
            -   name: Build
                env:
                    CI: true
                run: |
                    ./gradlew --no-daemon verifyPlugin
