name: Build and Verify Plugin

on:
    push:
        branches: '*'
        tags-ignore: '*'

jobs:
    build:
        name: Build and Verify Plugin
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.4
            -   name: Setup Java
                uses: actions/setup-java@v1.4.3
                with:
                    java-version: 11.x
            -   name: Use Gradle Cache
                uses: actions/cache@v2.1.3
                with:
                    path: ~/.gradle/caches
                    key: ${{ runner.os }}-gradle
            -   name: Build
                env:
                    CI: true
                run: |
                    ./gradlew --no-daemon verifyPlugin
