name: Build and Verify Plugin

on:
    push:
        branches: '*'
        tags-ignore: '*'
    pull_request:
        branches: '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build and Verify Plugin
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout
                uses: actions/checkout@v4.2.2
            -   name: Setup Java
                uses: actions/setup-java@v4.7.1
                with:
                    java-version: 21.x
                    distribution: temurin
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Build
                env:
                    CI: true
                run: |
                    ./gradlew --no-daemon :move-tab-plugin:verifyPlugin
            -   name: Predict Next Version
                id: semrel
                uses: go-semantic-release/action@v1
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    dry: true
            -   name: Show Predicted Version
                run: |
                    echo "### Predicted Release Version" >> "$GITHUB_STEP_SUMMARY"
                    echo "" >> "$GITHUB_STEP_SUMMARY"
                    echo "Next release version if created from this commit: **${{ steps.semrel.outputs.version }}**" >> "$GITHUB_STEP_SUMMARY"
